version: "3"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    tty: true
    healthcheck:
      test: ["CMD","pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 10
