---
openapi: 3.0.3
info:
  title: revolver
  version: 1.0.0
servers: []
paths:
  "/api/monsters":
    get:
      summary: index
      tags:
      - Api::Monster
      responses:
        '200':
          description: returns http success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
              example:
              - id: 1
                name: レアコイル
                description: ニビシティ
                created_at: '2023-01-05T11:08:22.817+09:00'
                updated_at: '2023-01-05T11:08:22.817+09:00'
