default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%=  ENV.fetch("RAILS_MAX_THREADS") { 8 } %>
  host: <%= ENV['DATABASE_URL'] %>
  password: password
development:
  <<: *default
  database: revolver_development
test:
  <<: *default
  host: '127.0.0.1'
  database: revolver_test
production:
  <<: *default
  database: revolver_production
  username: revolver
  password: <%= ENV["REVOLVER_DATABASE_PASSWORD"] %>
