default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%=  ENV.fetch("RAILS_MAX_THREADS") { 8 } %>
  host: <%= ENV['OPERATION_DB_HOST'] %>
development:
  <<: *default
  database: operation_controller_development
test:
  <<: *default
  database: operation_controller_test
production:
  <<: *default
  database: operation_controller_production
  username: operation_controller
  password: <%= ENV["OPERATION_CONTROLLER_DATABASE_PASSWORD"] %>
