name: "API: Generate Openapi Schema"

on:
  push:
    branches:
      - main
    paths:
      - "app/controllers/api/**"
      - "spec/requests/api/**"
      - ".github/workflows/api_generate_openapi.yaml"
      - ".github/workflows/openapi-generater.yaml"
  workflow_dispatch:
    inputs:
      environment:
        description: Development Environment
        required: true
        type: environment

jobs:
  ci:
    name: Generate Openapi Schema
    uses: ./.github/workflows/openapi-generater.yaml
    with:
      app_name: api
