name: "Application: CI"

on:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy env
        run: cp .env.template .env

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      - name: Build DB image
        run: docker compose -f docker-compose-ci.yml build

      - name: Start DB container
        run: docker compose -f docker-compose-ci.yml build

      - name: Create database and load schema
        env:
          RAILS_ENV: test
          EC_DATABASE_PORT: 3310
        run: bundle exec rails db:create db:migrate

      - name: Bundle install
        run:  bundle install --jobs=4 --retry=3

      - name: Run lint
        run: bundle exec rubocop

      - name: Run test
        run: bundle exec rspec
